name = input("Enter the name")
branch = input("Enter your branch")
gender = input("ENter you gender")
college = input("Enter your college name")
age = input("Enter your age")

print("Name: ",name)
print("Branch: ",branch)
print("Gender: ",gender)
print("College: ",college)
print("Age: ",age)
